// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_8wFexi8vjgQSITp2nrn11epw4fMQl0E',
    appId: '1:79254898338:web:28e530513ecce656daf9fb',
    messagingSenderId: '79254898338',
    projectId: 'appmyname-858d6',
    authDomain: 'appmyname-858d6.firebaseapp.com',
    storageBucket: 'appmyname-858d6.firebasestorage.app',
    measurementId: 'G-6BN0B19S10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEw_Ggd4gT9qg78fvhhT9rf-oi1eA5p3M',
    appId: '1:79254898338:android:2b66dea02ea95d9adaf9fb',
    messagingSenderId: '79254898338',
    projectId: 'appmyname-858d6',
    storageBucket: 'appmyname-858d6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-WQZxHu9l9dE-z22iWMvhyfLBUgNiGyU',
    appId: '1:79254898338:ios:59d6a61bf2885c9ddaf9fb',
    messagingSenderId: '79254898338',
    projectId: 'appmyname-858d6',
    storageBucket: 'appmyname-858d6.firebasestorage.app',
    androidClientId: '79254898338-4rmcs90u5jlp8lanhp6tfb03t4rulq1f.apps.googleusercontent.com',
    iosClientId: '79254898338-fanr486ohied4js9q8lqlu0hjjr0r2eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-WQZxHu9l9dE-z22iWMvhyfLBUgNiGyU',
    appId: '1:79254898338:ios:59d6a61bf2885c9ddaf9fb',
    messagingSenderId: '79254898338',
    projectId: 'appmyname-858d6',
    storageBucket: 'appmyname-858d6.firebasestorage.app',
    androidClientId: '79254898338-4rmcs90u5jlp8lanhp6tfb03t4rulq1f.apps.googleusercontent.com',
    iosClientId: '79254898338-fanr486ohied4js9q8lqlu0hjjr0r2eb.apps.googleusercontent.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_8wFexi8vjgQSITp2nrn11epw4fMQl0E',
    appId: '1:79254898338:web:13a71cf5366c51afdaf9fb',
    messagingSenderId: '79254898338',
    projectId: 'appmyname-858d6',
    authDomain: 'appmyname-858d6.firebaseapp.com',
    storageBucket: 'appmyname-858d6.firebasestorage.app',
    measurementId: 'G-TZQF95229V',
  );
}
